name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps 

      - name: Run Playwright tests
        run: npx playwright test

      - name: Generate Allure report
        run: npx allure generate --clean

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report/

  allure:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Allure history
        uses: actions/checkout@v4
        with:
          ref: main
          path: allure-history

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        with:
<<<<<<< HEAD
          allure_results: allure-results
=======
          allure_results: ./allure-results
          gh_pages: gh-pages
          allure_report: allure-report
>>>>>>> 6a2b1fd (fix 9)
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
